//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myAbdulKadr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int ID { get; set; }
        public int empID { get; set; }
        public string countryName { get; set; }
        public string cityName { get; set; }
        public string address1 { get; set; }
        public int type { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
