//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public int ID { get; set; }
        public int empID { get; set; }
        public Nullable<int> educationType { get; set; }
        public Nullable<int> grade { get; set; }
        public string educationCentreName { get; set; }
        public string faculty { get; set; }
        public string speciality { get; set; }
        public Nullable<int> endYear { get; set; }
        public string diplomNumber { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
