//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_LIST
    {
        public Nullable<bool> isfired { get; set; }
        public int ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string secondname { get; set; }
        public System.DateTime birthdate { get; set; }
        public string position { get; set; }
        public string birthplace { get; set; }
    }
}
