//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeActivity
    {
        public int ID { get; set; }
        public int empID { get; set; }
        public string activityText { get; set; }
        public Nullable<System.DateTime> issueDate { get; set; }
        public string activityType { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
