//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hydrogen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string secondname { get; set; }
        public string sex { get; set; }
        public System.DateTime birthdate { get; set; }
        public string birthplace { get; set; }
        public Nullable<byte> familyStatusID { get; set; }
        public string passportSerial { get; set; }
        public string passportNumber { get; set; }
        public string FINCODE { get; set; }
        public Nullable<int> nationalityID { get; set; }
        public Nullable<int> partyID { get; set; }
        public Nullable<int> photoID { get; set; }
    }
}
