//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public int ID { get; set; }
        public int empID { get; set; }
        public Nullable<int> orgID { get; set; }
        public Nullable<int> deptID { get; set; }
        public Nullable<int> sectID { get; set; }
        public bool isMain { get; set; }
        public string positionName { get; set; }
        public System.DateTime beginDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        public virtual section section { get; set; }
        public virtual employee employee { get; set; }
    }
}
