//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reproval
    {
        public int ID { get; set; }
        public byte rType { get; set; }
        public int empID { get; set; }
        public string rDefinition { get; set; }
        public string rNotes { get; set; }
        public System.DateTime rDate { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
