//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int employeeID { get; set; }
        public decimal baseSalary { get; set; }
        public decimal dosentBase { get; set; }
        public decimal dosentPercent { get; set; }
        public decimal professorBase { get; set; }
        public decimal professorPercent { get; set; }
        public decimal academicBase { get; set; }
        public decimal academicPercent { get; set; }
        public decimal scientceDoctorBase { get; set; }
        public decimal scientceDoctorPercent { get; set; }
        public decimal scienceCandadateBase { get; set; }
        public decimal scienceCandadatePercent { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
