//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Position
    {
        public int ID { get; set; }
        public string structName { get; set; }
        public string positionName { get; set; }
        public bool ismain { get; set; }
        public System.DateTime begindate { get; set; }
        public int empID { get; set; }
    }
}
